In [ ]:
Made By @Heramb.0x1
DMs are Open  : https://www.linkedin.com/in/heramb0x1/

In [1]:
import cv2 
import numpy as np

In [2]:
!pip install opencv-python

In [3]:
!pip install opencv-python --user

In [4]:
img = cv2.imread("D:\OpenCV (CV-Computer Vision) Project\Happy Boy.png")

In [5]:
# Blur using Filter2D
kernel = np.ones((5,5), np.float32) / 25
print(kernel)


[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [6]:
# Filter2D
smoothed = cv2.filter2D(img, -1, kernel)

# Average Blur
img_blur = cv2.blur(img, (5,5))

# Median Blur
m_blur = cv2.medianBlur(img, 7)

# Gaussian Blur, sigmaX(stdDev)= 1
g_blur = cv2.GaussianBlur(img, (7,7), 1)

cv2.imshow('Original', img)
cv2.imshow('Blur', smoothed)
cv2.imshow('average', img_blur)
cv2.imshow('median', m_blur)
cv2.imshow('gaussian', g_blur)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()